# Default values for keycloak-image-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: keycloak
customImage: false
useAWSJDBCWrapper: true
jdbcWrapperURL: https://github.com/awslabs/aws-advanced-jdbc-wrapper/releases/download/2.5.6/aws-advanced-jdbc-wrapper-2.5.6.jar
keycloakImage: quay.io/remerson/keycloak@sha256:cb6289ff0fd6b39565afaa7a580fa3e84f0438dd42552ac36f7f4e0e6bf9039b
