name: ROSA Daily Scheduled Run

on:
  schedule:
    - cron: '0 5 * * 1-5' # Runs At 05:00 UTC on every day-of-week from Monday through Friday.
  workflow_dispatch:

# env:
#   CLUSTER_PREFIX: gh-keycloak

jobs:
  cluster:
    name: ROSA Scheduled Create cluster
    uses: ./.github/workflows/rosa-multi-az-cluster-create.yml
    with:
      clusterPrefix: gh-ryan # ${{ env.CLUSTER_PREFIX }} -- unfortunately 'env.' doesn't work here
      region: eu-north-1
    secrets: inherit

  run-functional-tests:
    needs: cluster
    uses: ./.github/workflows/rosa-run-crossdc-func-tests.yml
    with:
      clusterPrefix: gh-keycloak # ${{ env.CLUSTER_PREFIX }} -- unfortunately 'env.' doesn't work here
    secrets: inherit

  run-scaling-benchmark:
    needs: run-functional-tests
    uses: ./.github/workflows/rosa-scaling-benchmark.yml
    with:
      clusterName: gh-keycloak-a # ${{ env.CLUSTER_PREFIX }}-a -- unfortunately 'env.' doesn't work here ${{ env.CLUSTER_PREFIX }}-a
      skipCreateDeployment: true
      skipDeleteProject: true
    secrets: inherit
